global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "electronic-locker-system"
    scheme: https
    static_configs:
      - targets: ["electronic-locker-system-k1l8.vercel.app"]
    metrics_path: "/api/metrics"
